/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.geepawhill.wordle

import javafx.application.Application
import javafx.scene.Parent
import javafx.scene.Scene
import javafx.stage.Screen
import javafx.stage.Stage
import org.geepawhill.wordle.utilities.StringUtils

import org.apache.commons.text.WordUtils
import tornadofx.*

class WordleView : View() {
    override val root = borderpane { }

}

class App : Application() {

    override fun start(primaryStage: Stage?) {
        val controller = primaryStage!!
        val wordleView = WordleView()
        controller.scene = Scene(wordleView.root)
        controller.isMaximized=true
        controller.show()
    }
}


fun main(args:Array<String>) {
    Application.launch(App::class.java, *args)
}
