/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.geepawhill.wordle

import javafx.application.Application
import javafx.scene.Scene
import javafx.stage.Stage


class Main : Application() {

    override fun start(primaryStage: Stage?) {
        val controller = primaryStage!!
        val mainView = MainView()
        controller.scene = Scene(mainView.root)
        controller.isMaximized = true
        controller.show()
    }
}


fun main(args: Array<String>) {
    Application.launch(Main::class.java, *args)
}
