/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.geepawhill.wordle.kotlin-library-conventions")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.0")
    testImplementation("org.assertj:assertj-core:3.23.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.0")
}